### ISSUE TITLE
Slider comentarios

### ISSUE THREAD

**Issue by margarcuae** [rocoto-tech/Transportes-Landing-page#1]
Falta slider de los comentarios en clientes felices

**Comment by luisbch9** [comment]
Done

**Comment by margarcuae** [comment]
El tamaño de las comillas es muy grande ... las proporcionaes no están correctas 
![image](https://user-images.githubusercontent.com/18340241/89722925-1d2cba80-d9b5-11ea-87d0-83f4e5f9bd52.png)

debería ser algo así 
![image](https://user-images.githubusercontent.com/18340241/89722930-2c136d00-d9b5-11ea-982d-5a00831d3e33.png)

**Comment by luisbch9** [comment]
![image](https://user-images.githubusercontent.com/15067649/89723137-ff148980-d9b7-11ea-8428-0443a8964aab.png)

Confirm to Close Issue
