### ISSUE TITLE
Comportamiento de barra de navegación

### ISSUE THREAD

**Issue by jhuni45** [rocoto-tech/Transportes-Landing-page#10]
*Describe lo que tiene que ser cambiado incluye capturas del antes y después*
### Página de referencia
[https://palmyra-dev.web.app/#/](https://palmyra-dev.web.app/#/)

![image](https://user-images.githubusercontent.com/11915191/89905080-4f097100-dbaf-11ea-9196-c3fb903fd665.png)

Con respecto a la imagen de arriba 

- [x] La barrita azul que desaparece, debe encogerse antes
- [x] La parte blanca debe tener:
     - [x] Efecto de tamaño de logo y barra
     - [x] Los textos del menú deben estar centrado con respecto al logo
- [x] Agregar un sombreado o elevación en la parte inferior -> Consular figma  (Se ve muy planito)
- [x] Corregir el "contacto" a "Contacto"
- [x] Agregar un sombreado al botón de "Cotiza aquí" (Este tambien debe dirigir a la ventana del whatsapp)
 
### Con respecto a la ventana del whatsap, que abra una nueva y no sobre la misma
- [x]  new tab wsp

**Comment by luisbch9** [comment]
Confirm to Close
