### ISSUE TITLE
Animacion y corrección de "Valores"

### ISSUE THREAD

**Issue by jhuni45** [rocoto-tech/Transportes-Landing-page#11]
*Describe lo que falta con capturas si es necesario*
![image](https://user-images.githubusercontent.com/11915191/89910986-86c7e700-dbb6-11ea-976e-0e5ffc3b0731.png)

- [x] Si el texto es muy grande, ponerlo en dos líneas
- [x] Las animaciones, efecto caída
- [x] Espaciado con respecto a los nombres de valores y la parte gris de "servicio de calidad" (Que sea el mismo que existe entre el titulo de "nosotros" y la mision)

**Comment by luisbch9** [comment]
Close ?
