### ISSUE TITLE
Efecto en el botón de "enviar mensaje"

### ISSUE THREAD

**Issue by jhuni45** [rocoto-tech/Transportes-Landing-page#13]
*Describe lo que falta con capturas si es necesario*
![image](https://user-images.githubusercontent.com/11915191/89912046-bcb99b00-dbb7-11ea-9177-f1c4b2037578.png)

- [x] El títuo debe conservar las dos líneas (Tal vez reducir un poco el texto)
- [x] La animación del botón ha de ser igual a -> [http://www.yichang.com.pe/#contacto](http://www.yichang.com.pe/#contacto)

**Comment by luisbch9** [comment]
Confirm to close issue
