### ISSUE TITLE
[Móvil] Generales

### ISSUE THREAD

**Issue by jhuni45** [rocoto-tech/Transportes-Landing-page#15]
*Describe lo que tiene que ser cambiado incluye capturas del antes y después*
![image](https://user-images.githubusercontent.com/11915191/89913765-b88e7d00-dbb9-11ea-8482-b6cd9513d4ce.png)

- [x] Los títulos deben conservar el rectangulo naranja (Se acordó modificar el tamaño del texto, conservar la alineacion a la derecha del texto)
- [x] Todos los contenidos que no sean títulos o subtitulos, deben estar ahora centrados

### Con respecto a los botones flotantes
![image](https://user-images.githubusercontent.com/11915191/89920908-a2d18580-dbc2-11ea-8bdd-725cc737cb35.png)

- [x] Para móvil debe aparecer ahora un botón a la izquierda el cual : 
     - Si presiono debe desplazar a la parte superior
     - El color es *FF8212* con 85% de opacidad -> Consultar figma en el frame "Colores"
     - Solo aparece cuando deslizo hacia abajo

**Comment by luisbch9** [comment]
Done.
