### ISSUE TITLE
Menu interno de los servicios

### ISSUE THREAD

**Issue by jhuni45** [rocoto-tech/Transportes-Landing-page#18]
*Describe lo que falta con capturas si es necesario*
![image](https://user-images.githubusercontent.com/11915191/89923700-99e2b300-dbc6-11ea-99d5-e66f2c24506d.png)

- [x] Agregar el efecto cuando el mouse este sobre las opciones

## Colocar los textos e imágenes que están en el figma

**Comment by luisbch9** [comment]
Done
