### ISSUE TITLE
[Móvil] Sección de clientes

### ISSUE THREAD

**Issue by jhuni45** [rocoto-tech/Transportes-Landing-page#28]
*Describe lo que tiene que ser cambiado incluye capturas del antes y después*
[Imagen antes]
![imagen](https://user-images.githubusercontent.com/11915191/90166588-19f05080-dd60-11ea-8548-36abcc6b1ac6.png)

[Imagen despues]
![imagen](https://user-images.githubusercontent.com/11915191/90166495-f3cab080-dd5f-11ea-8c91-8553330ba59c.png)

- [ ] que ahora solo conserve un signo en la parte de arriba

**Comment by margarcuae** [comment]
eso no está dentro del trato.
