### ISSUE TITLE
[Movil] Seccion de personal

### ISSUE THREAD

**Issue by jhuni45** [rocoto-tech/Transportes-Landing-page#29]
*Describe lo que tiene que ser cambiado incluye capturas del antes y después*
![imagen](https://user-images.githubusercontent.com/11915191/90166724-486e2b80-dd60-11ea-90a4-cf36d59ba452.png)

- [ ] Debe estar en dos columnas

**Comment by margarcuae** [comment]
está en dos columnas 
![image](https://user-images.githubusercontent.com/18340241/90202882-99a00e80-dda4-11ea-9012-89f605b85c94.png)
