### ISSUE TITLE
Cambio de la barra de navegación

### ISSUE THREAD

**Issue by jhuni45** [rocoto-tech/Transportes-Landing-page#3]
*Describe lo que tiene que ser cambiado incluye capturas del antes y después*
# Cambio del color y animación de la barra con los menús
[Imagen - antes]
![image](https://user-images.githubusercontent.com/11915191/89686304-bda2b200-d8c3-11ea-814e-6a335beb5b88.png)

[Image - después]

![image](https://user-images.githubusercontent.com/11915191/89690830-132f8c80-d8cd-11ea-8b8f-1e5043901d11.png)

### La barra ahora será de color blanco, el logo que se ve, es el oficial (respetar ese margen izquierdo que está en el Figma). 

Los estados de los menús son (bolitas rojas):

1. Cuando se encuentra en esa sección ==> Color del texto que está en el Figma (azul)
2. Cuando se pasa el cursor ==> Color del texto que está en el Figma (azul), dibujar una barra del mismo color bajo el texto, pegado al borde de la barra
3. Solo para "Servicios" ==> Se mostrará un submenú  originado al limite exterior de la barra
4. Cuando no tiene ninguna acción
5. Opción del submenú cuando esta el cursor encima

**Comment by luisbch9** [comment]
Done
