### ISSUE TITLE
[Móvil general] Con respecto a títulos 

### ISSUE THREAD

**Issue by jhuni45** [rocoto-tech/Transportes-Landing-page#30]
*Describe lo que tiene que ser cambiado incluye capturas del antes y después*
![imagen](https://user-images.githubusercontent.com/11915191/90166838-6f2c6200-dd60-11ea-8f8b-a13f7e940771.png)

- [x] Se ve bien que el texto este pegado a la derecha pero tal vez te diga que este pegado al cuadro naranja, como el web 
- [x] Aumentar un poco se espaciado entre el titulo y el texto de esa sección
- [x] La animacion del texto

**Comment by margarcuae** [comment]
1. Lo acerqué un poco más, pero debido a que no todos los textos son del mismo tamaño, algunos se verán más alejados.
2. ok 
3. Pertenece a otro issue
