### ISSUE TITLE
Al hacer clic al logo no redirige al inicio

### ISSUE THREAD

**Issue by jhuni45** [rocoto-tech/Transportes-Landing-page#35]
**Describe the bug**

## Tanto en versión web como móvil
![imagen](https://user-images.githubusercontent.com/11915191/90299009-09240580-de5a-11ea-902f-41dc3c279ffa.png)
![imagen](https://user-images.githubusercontent.com/11915191/90299055-2c4eb500-de5a-11ea-8aca-4ca715643f54.png)

**Comment by luisbch9** [comment]
Done
