### ISSUE TITLE
Opcion de submenu del footer no desplaza a la sección

### ISSUE THREAD

**Issue by jhuni45** [rocoto-tech/Transportes-Landing-page#36]
**Describe the bug**
![imagen](https://user-images.githubusercontent.com/11915191/90299098-5e601700-de5a-11ea-8541-08c00a62cd34.png)

La opción de "Mision y Vision" no hace nada

- [x] Este deberia desplazar a la seccion de "Nosotros" de la pagina

**Comment by luisbch9** [comment]
Done
