### ISSUE TITLE
Cambios menores de colores del pie de página

### ISSUE THREAD

**Issue by jhuni45** [rocoto-tech/Transportes-Landing-page#4]
*Describe lo que tiene que ser cambiado incluye capturas del antes y después*

## Los colores de los íconos y ahora tienen que dirigir a algún link
[Imagen - antes]
![new foot](https://user-images.githubusercontent.com/11915191/89712347-ed9a9580-d955-11ea-9f88-1a12d58a1f42.png)

[Imagen - despues]
![new foot2](https://user-images.githubusercontent.com/11915191/89712359-f723fd80-d955-11ea-82de-efed24a5c9af.png)

El logo que se muestra es el oficial

### Consideraciones:
* En la parte de "Nosotros", la sección <<Grupo Palmyra>> al hacer click que me dirija al inicio de la página (con un desplazamiento suave)
      - En la sección <<Misión y vision>> al hacer click queme dirija a la parte de "Nosotros"

* Los íconos de las redes sociales son color naranja, al pasar el cursor debe cambiar a color negro (Ya les envié las imágenes)

### Observación
![image](https://user-images.githubusercontent.com/11915191/89712463-9ea13000-d956-11ea-94e2-615cdc439c15.png)

En la página que me pasaron el espacio entre iconos y texto es muy reducido, aumentar por favor

**Comment by margarcuae** [comment]
Los cambios fueron realizados
