### ISSUE TITLE
[Cambio pequeño] Modificación de tamaño de imágenes

### ISSUE THREAD

**Issue by jhuni45** [rocoto-tech/Transportes-Landing-page#5]
*Describe lo que tiene que ser cambiado incluye capturas del antes y después*
##  El tamaño de las imágenes del carrusel no debería recortarse, mostrar todo.
[Imagen de la página]
![image](https://user-images.githubusercontent.com/11915191/89712636-c2b14100-d957-11ea-87d8-19b5eacbcfab.png)

[Imagen del Figma]
![image](https://user-images.githubusercontent.com/11915191/89712680-02782880-d958-11ea-9f35-ecc496e6b8d0.png)

### Observación
Yo le explique al chico de la empresa que eso se escala según las dimensiones de la imagen, pero me indicó que si es necesario pasar las imágenes con mejores dimensiones pues no hay problema

**Comment by margarcuae** [comment]
Hola Junior el tamaño de la imagen ya fue corregio, lo revisas por favor para cerrar el _issue_. 
De todos modos **El tamaño siempre va a variar**  un poco por el tamaño de las pantallas.
