### ISSUE TITLE
Botón de WhatsApp

### ISSUE THREAD

**Issue by jhuni45** [rocoto-tech/Transportes-Landing-page#6]
*Describe lo que falta con capturas si es necesario*
### El comportamiento de la barra de navegación: debe desaparecer la primera parte y al mismo momento aparecer un botón flotante con el ícono de whatsapp
![whatsapp](https://user-images.githubusercontent.com/11915191/89712814-ee80f680-d958-11ea-8c49-e9fb5ac2672f.png)

**Comment by luisbch9** [comment]
Check to close Issue
